import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import '../../../../core/theme/app_text_style.dart';
import '../../../../core/theme/app_theme.dart';
import '../../../../core/theme/color.dart';

class ProseSection extends StatelessWidget {
  const ProseSection({
    required this.heading,
    required this.body,
    this.aiGenerated = false,
    super.key,
  });

  final String heading;
  final String body;
  final bool aiGenerated;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          heading,
          style: AppTextStyle.sectionTitle.copyWith(color: AppColors.ink),
        ),
        Insets.sm.verticalSpace,
        Text(body, style: AppTextStyle.body.copyWith(color: AppColors.ink)),
        if (aiGenerated) ...[
          Insets.xs.verticalSpace,
          Text(
            'Summary generated by AI',
            style: AppTextStyle.statLabel.copyWith(color: AppColors.inkFaint),
          ),
        ],
      ],
    );
  }
}
